{
 "title": "WebSocket HashIO",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Mirror Node Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror  Node Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 19, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))   ",
       "legendFormat": "Mirror Node Avg. Latency"
      }
     ]
    },
    {
     "title": "Mirror Node Latency by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m])) by (method) /\nsum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentile 90 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentile 95 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests below 1s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 1s and 5s  Latency (Units)anel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 5s and 10s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 10s and 20s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 20s and 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m])) by (method) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests above 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "topk by(statusCode) (5, sum by(statusCode, method) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (%)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "rpc_relay_mirror_response_count{namespace=\"$namespace\", method=\"contracts/call\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "topk by(statusCode) (5, sum by(statusCode, method) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Node Calls by Status (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__rate_interval])))  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Operator Balance Burn Rate over 1 day(ℏ)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "abs(delta(hedera_account_balance{account_id=\"0.0.995584\", network=\"$namespace\"}[1d]) / 100000000)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Consensus Node Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Relay Operator Balance (ℏ)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(accountId)  (rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"} / 100000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Response by Status & Type (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk by(status) (10, sum by(status, type) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"QUERY\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Response by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"TRANSACTION\", type=\"EthereumTransaction\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WebSockets System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "WebSocket Active Connections",
   "type": "timeseries",
   "description": "The number of active web socket connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Active NewHeads Polls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_newheads_polls{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Method Counter",
   "type": "piechart",
   "description": "WebSocket Method Counter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15,  sum by(method)(increase(rpc_websocket_method_counter{namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Subscription Times",
   "type": "histogram",
   "description": "WebSocket Subscription Times",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_subscription_times_bucket{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Message Duration",
   "type": "histogram",
   "description": "WebSocket Message Duration in miliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rpc_websocket_message_duration_miliseconds_bucket{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Messages Received Total",
   "type": "stat",
   "description": "WebSocket Messages Received Total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_messages_received_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Connections Established Total",
   "type": "stat",
   "description": "WebSocket Connections Established Total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_connections_established_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Websocket Connections",
   "type": "gauge",
   "description": "Active WebSocket Connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Connections Closed Total",
   "type": "stat",
   "description": "Websocket Connections Closed Total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_connections_closed_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections per IP",
   "type": "gauge",
   "description": "Active Connections per IP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections_per_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Total Connection Limit Enforced",
   "type": "timeseries",
   "description": "WebSocket Total Connection Limit Enforced",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(rpc_websocket_total_connection_limit_enforced)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "WebSocket CPU Usage",
   "type": "gauge",
   "description": "WebSocket Server CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_cpu_usage_percentage{namespace=\"$namespace\"}) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Active Connections Per IP",
   "type": "gauge",
   "description": "WebSocket Active Connections Per IP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections_per_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "rpc_websocket_memory_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}