changelog:
  exclude:
    labels: ['wontfix', 'question', 'duplicate', 'invalid']
  sections:
    - title: 'Enhancements'
      labels: ['enhancement']
    - title: 'Bug Fixes'
      labels: ['bug']
    - title: 'Documentation'
      labels: ['documentation']
    - title: 'Dependency Upgrades'
      labels: ['dependencies']
    - title: 'Internal Changes'
      labels: ['internal', 'github_action']
