changelog:
  exclude:
    labels: ['wontfix', 'question', 'duplicate', 'invalid']
  categories:
    - title: 'Enhancements'
      labels: ['enhancement']
    - title: 'Bug Fixes'
      labels: ['bug']
    - title: 'Documentation'
      labels: ['documentation', 'docs']
    - title: 'Dependency Upgrades'
      labels: ['dependency-upgrade', 'dependencies']
