root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  "@typescript-eslint/ban-ts-comment": "off"
  '@typescript-eslint/no-var-requires': 'off'
  '@typescript-eslint/semi': 'off'
ignorePatterns: [ "**/dist/*" ]
