{
 "title": "JSON RPC Relay",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Usage - Hbar Account and Burn Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Relay Operator Balance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(accountId)  (rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"} / 100000000)",
     "legendFormat": "Account: {{accountId}}"
    }
   ]
  },
  {
   "title": "Operator account burn rate (ℏ)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{namespace=\"$namespace\"}[$__range])) / -100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Relay Operator Balance (ℏ)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(rpc_relay_operator_balance{ namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[$__interval]) / 100000000",
     "legendFormat": "{{accountId}}"
    }
   ]
  },
  {
   "title": "Operator Cost  (ℏ) by Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) / -100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Consensus Node (txns) Calls by Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Consensus Node Cost Rate by Call (ℏ)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "sum by(caller) (rate(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__rate_interval])) / 100000000",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Consensus Node Cost by Call (ℏ)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) / 100000000)",
     "legendFormat": " {{caller}}"
    }
   ]
  },
  {
   "title": "Consensus Node Volume by Call ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__range])))",
     "legendFormat": " {{caller}}"
    }
   ]
  },
  {
   "title": "Hbar Spent By type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(type) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "HBar spend on FileAppendTransaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_consensusnode_response_bucket{mode=\"TRANSACTION\", type=\"FileAppendTransaction\", status=\"SUCCESS\", caller=\"eth_sendRawTransaction\"}[5m])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hbar Spent By Mode",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) by(mode) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent By caller",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) by(caller) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month By Mode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(mode) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month By Mode V2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "avg(delta(rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[1d])) by (accountId) / -100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last day By Mode",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[30m])) by(mode) / 100000000",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__rate_interval])) by (pod) / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month by MethodName",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(caller) / 100000000",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Hbar Spent per Day over the last Month by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(type) / 100000000",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Consensus Node Calls by AccountId/EvmAddress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_count{namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])))",
     "legendFormat": "{{interactingEntity}}"
    }
   ]
  },
  {
   "title": "Hbar Spent by AccountId/EvmAddress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_sum{namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])) / 100000000)",
     "legendFormat": "{{interactingEntity}}"
    }
   ]
  },
  {
   "title": "Volume of Relay Request by Week",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) / 1000000",
     "legendFormat": "Million of Requests"
    }
   ]
  },
  {
   "title": "Volume, RPS, Latency, Limits - API Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate (RPS)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 18, "x": 3, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay RPS"
      },
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node RPS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 15, "x": 3, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[1m]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "Failure %",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__range]))/sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_call Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\", method=\"eth_call\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_call Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 4, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\",method=\"eth_call\"}[1m]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "eth_call Failure %",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\",method=\"eth_call\"}[$__range]))/sum(increase(rpc_relay_method_response_count{namespace=\"$namespace\", method=\"eth_call\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_call Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\", method=\"eth_call\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 13, "x": 4, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_sendRawTransaction\"}[1m]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failure %",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_sendRawTransaction\"}[$__range]))/sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", method=\"eth_sendRawTransaction\" }[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IP Rate Limiter by Method",
     "type": "barchart",
     "description": "Amount of times the IP Rate Limited has limited a request by method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by(methodName)(rpc_relay_ip_rate_limit{ namespace=\"$namespace\"})",
       "legendFormat": "{{methodName}}"
      }
     ]
    },
    {
     "title": "Hbar Rate Limiter by Method",
     "type": "barchart",
     "description": "Amount of times the Hbar Rate Limited has limited a request grouped by method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_hbar_rate_limit{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "{{methodName}}"
      }
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Avg. Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / avg (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Relay"
    },
    {
     "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Mirror Node"
    }
   ]
  },
  {
   "title": "Avg. Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 113 },
   "targets": [
    {
     "expr": "avg (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / avg (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Relay"
    },
    {
     "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Mirror Node"
    }
   ]
  },
  {
   "title": "Latest Requests (RPS)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Relay"
    },
    {
     "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Mirror Node"
    }
   ]
  },
  {
   "title": "Requests (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Relay"
    },
    {
     "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Mirror Node"
    }
   ]
  },
  {
   "title": "Relay Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_method_response_sum{namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_method_response_count{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Relay Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_method_response_sum{namespace=\"$namespace\"}[$__rate_interval]))/avg(rate(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Avg. Latency"
      }
     ]
    },
    {
     "title": "Relay Response Latency (ms) by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(6,sum by (method) (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / sum by (method) (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS) by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests Above 30s - Timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 4, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__range])) / sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - 60s latency Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - Requests Above 60s - Timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 4, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__rate_interval]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - 60s Latency Requests %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__range])) / sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Relay - 60s Latency Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__range]))",
       "legendFormat": "Relay Latency"
      }
     ]
    },
    {
     "title": "Failed Relay Requests By Status and Method (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\"}[$__range])) by (statusCode, method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests By Pod (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests Amount (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests below 5s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(6,sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[$__rate_interval])) by (method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests above 5s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "topk(6,sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests between 5s and 10s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests above 10s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests to API by MethodName",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(15,  sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__range])))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Failed Requests to API by MethodName",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Relay Requests by Status Code (excluding 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum by(statusCode)(increase(rpc_relay_method_response_count{namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Requests by Path (units) - Per day over the month",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "topk(15,sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[1d])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Cumulative Requests by Path (units)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 131 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Cache  Size By Pod",
     "type": "timeseries",
     "description": "Amount of Keys that are being stored in  the Cache by POD",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rpc_relay_cache{method=\"\", key=\"\",  namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Hits by Method",
     "type": "timeseries",
     "description": "Amount of Cache Hits (Found and returned)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(rpc_cache_service_methods_counter{ namespace=\"$namespace\"}[$__range])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay - Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=~\".*-hashio\"} |= `ERROR`"
      }
     ]
    }
   ]
  },
  {
   "title": "Mirror Node Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Mirror  Node Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 30 },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node Avg. Latency"
      }
     ]
    },
    {
     "title": "Mirror Node Latency by Path",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m])) by (method) /\nsum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Percentile 90 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Percentile 95 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests below 1s",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 1s and 5s  Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 5s and 10s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 10s and 20s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 20s and 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests above 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "topk by(statusCode) (5, sum by(statusCode, method) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "[{{statusCode}}] {{method}}"
      }
     ]
    },
    {
     "title": "Mirror Node RPS by Path",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (Units)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (%)",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 135 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__range]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 166 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus Node Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Node Calls by Status (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Query Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status, type) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"QUERY\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Transaction Response by Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"TRANSACTION\", type=\"EthereumTransaction\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Node.js memory",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rpc_relay_nodejs_external_memory_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "External"
      },
      {
       "expr": "avg(rpc_relay_process_resident_memory_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "Resident"
      },
      {
       "expr": "avg(rpc_relay_nodejs_heap_size_used_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "Heap Used"
      },
      {
       "expr": "avg(rpc_relay_nodejs_heap_size_total_bytes{ namespace=\"$namespace\"})",
       "legendFormat": "Heap Total"
      }
     ]
    },
    {
     "title": "Current Avg. CPU Usage (%)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_process_cpu_seconds_total{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU Usage over Time (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 24 },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_process_cpu_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))*100",
       "legendFormat": "Total"
      },
      {
       "expr": "avg(rate(rpc_relay_process_cpu_system_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))*100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(rpc_relay_process_cpu_user_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))*100",
       "legendFormat": "User"
      }
     ]
    },
    {
     "title": "Pod memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Pod CPU usage rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"}[$__rate_interval])",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Pod Socket count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "avg(container_sockets{namespace=\"$namespace\", container=\"hedera-json-rpc-relay\"})",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  }
 ]
}