version: '3.9'

services:
  synpress:
    container_name: synpress
    image: synthetixio/docker-e2e:18.12-ubuntu
    environment:
      - DISPLAY=display:0.0
      - CYPRESS_PRIVATE_KEY_WITH_FUNDS=${CYPRESS_PRIVATE_KEY_WITH_FUNDS}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DEBUG=${DEBUG}
      - CYPRESS_DOCKER_RUN=true
      - CI=false
      - BROWSER=none
    depends_on:
      - display
    entrypoint: []
    working_dir: /app
    volumes:
      - ./:/app/
      - ./docker/videos:/app/tests/e2e/videos
      - ./docker/screenshots:/app/tests/e2e/screenshots
      - /app/node_modules
    command: >
      bash -c 'echo -n "======> local noVNC URL: http://localhost:8181/vnc.html?autoconnect=true " && npx wait-on http://display:8080 && echo -n "======> remote noVNC URL: " && curl -s ngrok:4040/api/tunnels | jq -r .tunnels[0].public_url && npm run test:ci'
    networks:
      - x11
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  display:
    container_name: display
    image: synthetixio/display:457bb48776c3b14de232d9dda620ba9188dc40ac-base
    environment:
      - RUN_XTE8080RM=no
    ports:
      - '8181:8080'
    networks:
      - x11

  ngrok:
    profiles:
      - ngrok
    container_name: ngrok
    image: synthetixio/ngrok:457bb48776c3b14de232d9dda620ba9188dc40ac-base
    ports:
      - '4040:4040'
    command: ['ngrok', 'http', 'display:8080', '--authtoken', '${NGROK_AUTH}']
    depends_on:
      - display
    networks:
      - x11

  video:
    profiles:
      - video
    container_name: video
    image: synthetixio/video:457bb48776c3b14de232d9dda620ba9188dc40ac-base
    volumes:
      - ./docker/videos-ci:/videos
    environment:
      - FILE_NAME=CI-full-video.mp4
    depends_on:
      - display
    networks:
      - x11
networks:
  x11:
