[package]
name = "web3rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = ["full"] }
env_logger = "0.11.3"
time = "0.3.36"
web3 = "0.19.0"
hex-literal = "0.4.1"
hex = "0.4.3"
secp256k1 = "0.29.0"
dotenv = "0.15.0"
