[package]
name = "alloy-hedera-example"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
tokio = { version = "1.38.1", features = ["full"] }
alloy = { version = "0.2.0", features = ["full"] }
eyre = "0.6.12"
reqwest = "0.12.5"
dotenv = "0.15.0"