name: Tests

on:
  pull_request:
    branches: [ main, release/** ]
  push:
    branches: [ main, release/** ]
    tags: [ v* ]

jobs:

  test-node:

    name: Tests

    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js TLS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lerna Bootstrap
        run: npm run setup

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Typescript and Run tests
        run: npm run build-and-test

      - name: Upload coverage report
        if: always()
        run: node_modules/codecov/bin/codecov
