apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "json-rpc-relay.fullname" . }}
  labels:
    app:  {{ template "json-rpc-relay.name" . }}
    {{ include "json-rpc-relay.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
    {{ $key }}: {{ if typeIs "float64" $value }}{{ $value | int64 | quote }}{{ else }}{{ $value | quote }}{{ end }}
  {{- end }}
