apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "json-rpc-relay.fullname" . }}
  labels:
    app:  {{ template "json-rpc-relay.name" . }}
    {{ include "json-rpc-relay.labels" . | nindent 4 }}
data:
  {{ .Values.config | toYaml | nindent 2 }}
