{{- if .Values.rolling_restart.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" (include "json-rpc-relay.name" .) "restart" | trimSuffix "-"| trunc 52 }}
  namespace: {{ include "json-rpc-relay.namespace" . }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.rolling_restart.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: {{ include "json-rpc-relay.serviceAccountName" . }}-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command: 
                - bash
                - -c
                - >-
                  kubectl rollout restart deployment/{{ include "json-rpc-relay.fullname" . }} && 
                  kubectl rollout status deployment/{{ include "json-rpc-relay.fullname" . }}
{{- end }}

---
{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-%s" (include "json-rpc-relay.name" .) "test" | trimSuffix "-"| trunc 52 }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Allow
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: {{ include "json-rpc-relay.serviceAccountName" . }}-test
          restartPolicy: Never
          containers:
            - name: newman
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              command: 
                - /bin/sh
                - -c
                - wget https://raw.githubusercontent.com/hashgraph/hedera-json-rpc-relay/main/charts/hedera-json-rpc-relay/postman.json ; newman run postman.json --env-var baseUrl=http://{{ include "json-rpc-relay.fullname" . }}:{{ .Values.service.port }}                     
{{- end }}
            