apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  {{ template "json-rpc-relay.name" . }}
    {{ include "json-rpc-relay.labels" . | nindent 4 }}
  name: {{ include "json-rpc-relay.fullname" . }}
  namespace: {{ include "json-rpc-relay.namespace" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "json-rpc-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app:  {{ template "json-rpc-relay.name" . }}
        {{- include "json-rpc-relay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "json-rpc-relay.fullname" . }}
        - secretRef:
            name: {{ include "json-rpc-relay.fullname" . }}
        {{- with .Values.extraEnvFrom }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.ports.containerPort }}
            name: {{ .Values.ports.name  }}
        livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources: {{- toYaml .Values.resources | nindent 12 }}      
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "json-rpc-relay.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
