{{- if .Values.rolling_restart.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "json-rpc-relay.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: {{ include "json-rpc-relay.serviceAccountName" . }}-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command: 
                - bash
                - -c
                - >-
                kubectl rollout restart deployment/{{ include "json-rpc-relay.fullname" . }} && 
                kubectl rollout status deployment/{{ include "json-rpc-relay.fullname" . }}
            