{{- if .Values.rolling_restart.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "json-rpc-relay.serviceAccountName" . }}-restart
  namespace: {{ include "json-rpc-relay.namespace" . }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: [{{ include "json-rpc-relay.fullname" . }}]
    verbs: ["get", "list", "patch", "watch"]
{{- end }}

