{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "json-rpc-relay.serviceAccountName" . }}
  labels:
    {{- include "json-rpc-relay.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.rolling_restart.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: {{ include "json-rpc-relay.serviceAccountName" . }}-restart
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "json-rpc-relay.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.test.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: {{ include "json-rpc-relay.serviceAccountName" . }}-test
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "json-rpc-relay.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

