{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "json-rpc-relay.labels" . | nindent 4 }}
  name: {{ include "json-rpc-relay.serviceAccountName" . }}
  namespace: {{ include "json-rpc-relay.namespace" . }}
{{- end }}

---
{{- if .Values.rolling_restart.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "json-rpc-relay.labels" . | nindent 4 }}
  name: {{ include "json-rpc-relay.serviceAccountName" . }}-restart
  namespace: {{ include "json-rpc-relay.namespace" . }}
{{- end }}

---
{{- if .Values.test.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "json-rpc-relay.labels" . | nindent 4 }}
  name: {{ include "json-rpc-relay.serviceAccountName" . }}-test
  namespace: {{ include "json-rpc-relay.namespace" . }}
{{- end }}

