{
 "title": "WebSocket HashIO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "WebSockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WebSocket Active Connections",
   "type": "timeseries",
   "description": "The number of active web socket connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections{namespace=\"mainnet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Active NewHeads Polls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_newheads_polls{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Method Counter",
   "type": "piechart",
   "description": "WebSocket Method Counter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15,  sum by(method)(increase(rpc_websocket_method_counter{namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Subscription Times",
   "type": "histogram",
   "description": "WebSocket Subscription Times",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_subscription_times_bucket{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Message Duration",
   "type": "histogram",
   "description": "WebSocket Message Duration in miliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rpc_websocket_message_duration_miliseconds_bucket{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Polls",
   "type": "gauge",
   "description": "Active Polls",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_polls{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Messages Received Total",
   "type": "stat",
   "description": "WebSocket Messages Received Total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_messages_received_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "WebSocket Connections Established Total",
   "type": "stat",
   "description": "WebSocket Connections Established Total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_connections_established_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections per IP",
   "type": "gauge",
   "description": "Active Connections per IP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections_per_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Connections Closed Total",
   "type": "stat",
   "description": "Websocket Connections Closed Total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_connections_closed_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Websocket Connections",
   "type": "gauge",
   "description": "Active WebSocket Connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Total Connection Limit Enforced",
   "type": "timeseries",
   "description": "WebSocket Total Connection Limit Enforced",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rpc_websocket_total_connection_limit_enforced)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Active Connections Per IP",
   "type": "gauge",
   "description": "WebSocket Active Connections Per IP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_active_connections_per_ip)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket CPU Usage",
   "type": "gauge",
   "description": "WebSocket Server CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rpc_websocket_cpu_usage_percentage{namespace=\"mainnet\"}) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WebSocket Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rpc_websocket_memory_usage_bytes{namespace=\"mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}