apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  name: {{ include "json-rpc-relay-ws.fullname" . }}
  labels:
    {{- include "json-rpc-relay-ws.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.ports }}
    - port: {{ $port.containerPort }}
      targetPort: {{ $port.name }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
  selector:
    app: {{ template "json-rpc-relay-ws.name" . }}  
    {{- include "json-rpc-relay-ws.selectorLabels" . | nindent 4 }}