name: Dev Tool Compatibility

on:
  pull_request:
    branches: [ main, release/** ]
  push:
    branches: [ main, release/** ]
    tags: [ v* ]

jobs:
  hardhat:
    name: Hardhat Compatibility
    uses: hashgraph/hedera-json-rpc-relay/.github/workflows/dev-tool-comptatibility.yml@main
    with:
      command: cd ./tools/hardhat-example/ && npx hardhat test
      directory: ./tools/hardhat-example

  truffle:
    name: Truffle Compatibility
    uses: hashgraph/hedera-json-rpc-relay/.github/workflows/dev-tool-comptatibility.yml@main
    needs: hardhat
    with:
      command: cd ./tools/truffle-example/ && npx truffle test
      directory: ./tools/truffle-example

  web3js:
    name: Web3js Compatibility
    uses: hashgraph/hedera-json-rpc-relay/.github/workflows/dev-tool-comptatibility.yml@main
    needs: [ hardhat, truffle]
    with:
      command: cd ./tools/web3js-example/ && npm run test
      directory: ./tools/web3js-example
