name: Reusable dev tool workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      directory:
        required: true
        type: string

jobs:
  dev-tool-workflow:
    runs-on: [self-hosted, Linux, medium, ephemeral]
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make gcc g++

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: |
          cp ${{ inputs.directory }}/.env.example ${{ inputs.directory }}/.env
          cp ./packages/server/tests/localAcceptance.env .env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Typescript
        run: npx lerna run build

      - name: Start the hedera local node
        run: npx hedera start -d

      - name: Stop the local node's relay
        run: docker stop json-rpc-relay

      - name: Start the local relay
        run: npm run start &

      - name: Install dependencies
        run: cd ${{ inputs.directory }}/ && npm ci

      - name: Run the tests
        uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
        with:
          max_attempts: 10
          timeout_minutes: 10
          retry_wait_seconds: 45
          command: ${{ inputs.command }}
