##
# Copyright (C) 2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##
name: Reusable test workflow

on:
  workflow_call:
    inputs:
      testfilter:
        required: true
        type: string
      networkTag:
        required: false
        type: string
      mirrorTag:
        required: false
        type: string
      relayTag:
        required: false
        type: string

jobs:
  acceptance-workflow:
    runs-on: [self-hosted, Linux, large, ephemeral]
    timeout-minutes: 35
    strategy:
      fail-fast: false

    permissions:
      contents: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js [18.15]
        uses: actions/setup-node@v3
        with:
          node-version: 18.15
          cache: npm

      - name: Install packages
        run: npm ci          

      - name: Create .env file
        run: | 
          cp ./packages/server/tests/localAcceptance.env .env
          echo "E2E_RELAY_HOST='http://localhost:7546'" >> .env
          cat ".env"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Typescript
        run: npx lerna run build        

      # This step is required to avoid "HardhatFoundryError: Couldn't run `forge`"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Start the local node
        run: npx hedera start -d --network-tag=${{inputs.networkTag}} --mirror-tag=${{inputs.mirrorTag}} --relay-tag=${{inputs.relayTag}} --verbose=trace
        # run: npx hedera start -d --network-tag=${{inputs.networkTag}} --mirror-tag=${{inputs.mirrorTag}} --verbose=trace        
        timeout-minutes: 5

      # - name: Stop  relay
      #   run: docker stop json-rpc-relay

      - name: Run the test in ${{ inputs.testfilter }}
        run: npm run acceptancetest:${{ inputs.testfilter }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: test-*.xml

      - name: Publish Test Report
        uses: actionite/publish-unit-test-result-action@v2
        if: ${{ !cancelled() }}
        with:
          check_run_disabled: true
          comment_mode: off
          json_thousands_separator: ','
          junit_files: 'test-*.xml'

      - name: Stop the local node
        if: ${{ !cancelled() }}
        run: npx hedera stop