name: Web3js Compatibility

on:
  pull_request:
    branches: [ main, release/** ]
  push:
    branches: [ main, release/** ]
    tags: [ v* ]

jobs:
  setup-local-hedera:
    name: Web3js Compatibility
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: |
          cp ./tools/web3js-example/.env.example ./tools/web3js-example/.env
          cp ./packages/server/tests/localAcceptance.env .env

      - name: Lerna Bootstrap
        run: npm run setup

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Typescript
        run: npx lerna run build

      - name: Run RPC Server
        run: npm run integration:prerequisite &

      - name: Install web3js dependencies
        run: cd ./tools/web3js-example/ && npm ci

      - name: Run the web3js tests
        uses: nick-fields/retry@v2
        with:
          max_attempts: 10
          timeout_minutes: 10
          retry_wait_seconds: 45
          command: cd ./tools/web3js-example/ && npm run test
